wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.17.5
    framework: huggingface
    huggingface_version: 4.25.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1722766857
    t:
      1:
      - 1
      - 9
      - 11
      - 49
      - 55
      - 83
      - 103
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 63
      - 83
      - 103
      3:
      - 19
      - 23
      4: 3.10.13
      5: 0.17.5
      6: 4.25.1
      8:
      - 5
      13: linux-x86_64
learning_rate:
  desc: null
  value: 1.0e-05
iterations:
  desc: null
  value: 500
train_method:
  desc: null
  value: xattn
