wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.17.1
    framework: huggingface
    huggingface_version: 4.25.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717941859
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 83
      - 103
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 83
      - 103
      3:
      - 23
      4: 3.10.13
      5: 0.17.1
      6: 4.25.1
      8:
      - 5
      13: linux-x86_64
